### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by WardDeb** [maxplanck-ie/dissectBCL#1]
- [x] configs
- [x] detect new flowcell
  - [x] would need some smarter detection, right now we need to run both L1 and L2 again if L2 fails e.g.
- [x] flowcell class to keep all info
- [x] yaml dumper methodclass
- [x] bcl2convert
- [x] seq modalities  

Dont support this by default. ( shared modalities/lane --> multiple rounds )  

- [x] parkour int
- [x] unit tests
  - [x] misc tests
  - [ ] public bcl data ?!
  - [ ] figure out how to test communication functions
- [x] postFQ:
    - [x] fastqc
    - [x] multiqc
    - [x] clumper
        - [x] deal with logs
    - [x] fqScreen
    - [x] pdfReport.
 - [x] reads PF from flowcell bin files
 - [x] include hopped index stats if present
 - [x] fexsend check if file exists (purge on rerun)
